name: Security Scan

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  scan:
    uses: SFOE-prometheon/github-terraform-workflows/.github/workflows/ecr-build-scan-push.yml@v9
    with:
      dockerfile: Dockerfile.lambda
      build-context: .
      ecr-repository: drillapi
      image-tag: pr-${{ github.event.pull_request.number }}
      aws-region: eu-central-1
      scan-only: true
    secrets:
      aws-role: ${{ secrets.SFOE_DRILLAPI_PIPELINE_ROLE_DEV }}
